source 'https://github.com/CocoaPods/Specs.git'

target 'DVGAssetPickerController', :exclusive => true do
  pod "DVGAssetPickerController", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "DVGAssetPickerController", :path => "../"

  
end
